// ─── Database schema types (mirrors Supabase tables) ─────────────────────────

export type ProjectStatus = "active" | "completed" | "draft" | "paused";
export type PipelineType = "content" | "video";
// Review Queue (migration 014): draft → in_review → approved/rejected;
// scheduled/published are reserved for the future publisher.
export type ContentStatus =
  | "draft"
  | "in_review"
  | "approved"
  | "rejected"
  | "scheduled"
  | "published";

export interface StatusHistoryEntry {
  from: string;
  to: string;
  at: string;
  by: "user" | "worker" | "system";
  note?: string;
}
export type RenderStatus = "queued" | "rendering" | "done" | "failed";
export type ContentPlatform =
  | "linkedin"
  | "facebook"
  | "instagram"
  | "twitter"
  | "blog"
  | "email";

export type BrandStatus = "pending" | "researching" | "ready" | "failed";
export type ResearchJobStatus = "queued" | "running" | "done" | "failed";

// ─── BrandProfile — structured output of the Research agent ──────────────────

export interface BrandProfileService {
  name: string;
  description: string;
}
export interface BrandProfilePersona {
  name: string;
  role: string;
  goals: string[];
  pain_points: string[];
  channels: string[];
}
export interface BrandProfileVoice {
  tone: string[];                // ['authoritative','approachable']
  vocabulary_dos: string[];
  vocabulary_donts: string[];
  example_phrases: string[];
}
export interface BrandProfileAudience {
  demographics: string[];
  psychographics: string[];
  geographies: string[];
}
export interface BrandProfileICP {
  industries: string[];
  company_sizes: string[];       // ['SMB','Mid-market','Enterprise']
  roles: string[];
  pain_points: string[];
}

export interface BrandProfile {
  summary: string;
  positioning_statement: string;
  value_propositions: string[];
  services: BrandProfileService[];
  products: BrandProfileService[];
  offers: string[];
  brand_voice: BrandProfileVoice;
  audience: BrandProfileAudience;
  icp: BrandProfileICP;
  personas: BrandProfilePersona[];
  // Seed data the research agent emits alongside the profile.
  seed_keywords: string[];
  seed_competitors: string[];    // names only — the competitor agent enriches
}

// ─── Research job log entry ──────────────────────────────────────────────────

export interface ResearchLogEntry {
  ts: string;                    // ISO timestamp
  level: "info" | "warn" | "error" | "success";
  step: string;                  // matches DbBrandResearchJob.current_step values
  message: string;
  meta?: Record<string, unknown>;
}

// ─── Row types ────────────────────────────────────────────────────────────────

export interface DbProject {
  id: string;
  user_id: string;               // Clerk user id (text)
  name: string;
  type: PipelineType;
  status: ProjectStatus;
  created_at: string;
  updated_at: string;
  content_count: number;
  video_count: number;
  tags: string[];
  credits_used: number;
  brand_id: string | null;
}

export interface DbContentItem {
  id: string;
  project_id: string | null;
  // brand_id + user_prompt added in migration 003 to support the
  // direct-from-brand content generation flow (no project needed)
  brand_id?: string | null;
  user_prompt?: string | null;
  platform: ContentPlatform;
  title: string;
  preview: string | null;
  body: string | null;
  status: ContentStatus;
  created_at: string;
  // Engagement union: legacy social metrics OR generated-content extras
  // (hashtags + cta) the worker writes back. Either-or, depending on whether
  // the item was generated by the AI flow or imported/scraped.
  engagement:
    | { likes: number; shares: number; comments: number }
    | { hashtags?: string[]; cta?: string | null }
    | null;
  // V2 Phase 1.5 — evidence grounding + idea lineage (migration 010/011).
  // Optional: rows predating the migrations / non-idea-driven posts.
  grounded_on?: string[];
  topic_id?: string | null;
  // Review Queue (migration 014)
  review_note?: string | null;
  reviewed_at?: string | null;
  status_history?: StatusHistoryEntry[];
  // Publisher Foundation v1 (migration 015)
  scheduled_for?: string | null;
  published_at?: string | null;
  published_url?: string | null;
  platform_post_id?: string | null;
  /** 'manual' in v1; 'linkedin_api' | 'x_api' | 'facebook_api' | … later. */
  publishing_method?: string | null;
  /**
   * Per-creative branding overrides captured on /content/generate (migration
   * 019). Consumed by composeCreativeBrief. Optional: rows predate the column.
   */
  creative_branding?: {
    companyName?: string | null;
    founderName?: string | null;
    expertName?: string | null;
    useLogo?: boolean;
    useHeadshot?: boolean;
  } | null;
  // Campaign Execution Engine (Sprint 25, migration 030). Set when this item is
  // one asset of a campaign. Optional: rows predate the migration / standalone posts.
  campaign_id?: string | null;
  campaign_role?: string | null;
}

export interface DbRenderJob {
  id: string;
  project_id: string | null;
  name: string;
  status: RenderStatus;
  progress: number;
  started_at: string;
  completed_at: string | null;
  duration_ms: number | null;
  template: string;
  output_path: string | null;
  output_url: string | null;
  error_message: string | null;
  prompt: string | null;
  meta: Record<string, unknown> | null;
  // ─── migration 004 (merge) ──────────────────────────────────────────────────
  merged_video_url?: string | null;
  merge_status?: "pending" | "merging" | "done" | "failed" | null;
  merge_error?: string | null;
  // ─── migration 006 (full provenance + history) ──────────────────────────────
  user_id?: string | null;
  brand_id?: string | null;
  topic_id?: string | null;
  style?: string | null;
  script_json?: Record<string, unknown> | null;
  storyboard_json?: Record<string, unknown> | null;
  seo_json?: Record<string, unknown> | null;
  overlay_json?: { keywords: KeywordOverlay[] } | null;
  narration_url?: string | null;
  music_url?: string | null;
  music_track?: string | null;
  video_attribution?: string | null;
  created_at?: string;
}

export interface DbActivityItem {
  id: string;
  project_id: string | null;
  project_name: string | null;
  type:
    | "video_rendered"
    | "content_generated"
    | "project_created"
    | "approval"
    | "published"
    | "error"
    | "brand_researched";
  message: string;
  created_at: string;
  meta: Record<string, string> | null;
}

export interface DbBrand {
  id: string;
  user_id: string;
  name: string;
  website: string | null;
  industry: string | null;
  status: BrandStatus;
  profile: BrandProfile | null;
  brand_colors: Record<string, string> | null;
  logo_url: string | null;
  created_at: string;
  updated_at: string;
  // V2 Phase 1 — intelligence versioning + source attribution (migration 010)
  profile_version: number;
  /** Section → research_documents ids, e.g. { profile: [...], competitors: [...] } */
  profile_citations: Record<string, string[]>;
  last_research_run_id: string | null;
  /**
   * Creative Orchestrator (migration 018) — learning structure, READ-ONLY v1.
   * Shape documented in the migration: preferred_hierarchy /
   * platform_hierarchy / avoid_hierarchies / notes. Optional: rows predate
   * the migration until it's applied.
   */
  creative_preferences?: Record<string, unknown>;
}

// ─── Brand Assets (Creative Orchestrator Phase A — migration 017) ───────────
// User-uploaded LOCKED assets. Bytes are immutable, never sent to AI models,
// and the compositor may only resize/crop/mask/position them (see migration
// 017 header for the full safety contract).

// 'team_headshot' is future-ready (stored, but not consumed by v1 hierarchies).
export type BrandAssetKind = "logo" | "founder_headshot" | "team_headshot";

export interface DbBrandAsset {
  id: string;
  brand_id: string;
  kind: BrandAssetKind;
  /** For headshots this carries the person's display name (e.g. "Jane Doe — Founder"). */
  label: string | null;
  storage_path: string;
  public_url: string;
  mime_type: string;
  byte_size: number;
  width: number | null;
  height: number | null;
  has_alpha: boolean | null;
  /** Immutability flag — always true; uploaded bytes are never modified. */
  locked: boolean;
  created_at: string;
}

// ─── Content Creatives (Creative Orchestrator Phase B — migration 018) ──────
// One row per composed creative. creative_brief jsonb is the source of truth
// (shape: src/lib/creative/types.ts); hierarchy + confidence are denormalized
// for Phase D attribution. Status machine = the Creative Approval Gate:
// brief_ready → approved → generating → ready | failed, or brief_ready →
// rejected. Image generation is only reachable FROM 'approved'.

export interface DbContentCreative {
  id: string;
  content_item_id: string;
  brand_id: string;
  status: "brief_ready" | "approved" | "generating" | "ready" | "failed" | "rejected";
  /** CreativeBrief (src/lib/creative/types.ts) — kept loose here to avoid a client/server type dependency cycle. */
  creative_brief: Record<string, unknown>;
  creative_hierarchy: "founder_led" | "brand_led" | "data_led" | "quote_led" | "product_led";
  creative_confidence: number;
  platform: string;
  background_url: string | null;
  image_url: string | null;
  /** How the background was produced: 'imagen' (model) or 'fallback'
   *  (deterministic palette gradient when Imagen failed safety validation). */
  background_source: "imagen" | "fallback" | null;
  generation_error: string | null;
  generated_at: string | null;
  regen_count: number;
  status_history: StatusHistoryEntry[];
  created_at: string;
  updated_at: string;
  // Campaign Execution Engine (Sprint 25, migration 030). Set when this creative
  // is one asset of a campaign. Optional: rows predate the migration.
  campaign_id?: string | null;
  campaign_role?: string | null;
}

// ─── Campaigns (Campaign Execution Engine — Sprint 25, migration 030) ───────
// The PARENT of many creative assets. One request → a full strategically-
// aligned package. strategy = CampaignStrategy (src/lib/gemini.ts); qa = the
// Campaign QA snapshot (src/lib/creative/campaign-execution.ts). Assets link
// back via content_creatives.campaign_id.

export type CampaignStatus = "planning" | "generating" | "review" | "ready" | "failed";

export interface DbCampaign {
  id: string;
  user_id: string;
  brand_id: string;
  title: string | null;
  prompt: string;
  platform: string;
  status: CampaignStatus;
  /** CampaignStrategy — kept loose to avoid a client/server type cycle. */
  strategy: Record<string, unknown> | null;
  /** CampaignQA snapshot — kept loose for the same reason. */
  qa: Record<string, unknown> | null;
  asset_count: number;
  error: string | null;
  created_at: string;
  updated_at: string;
}

// ─── Research Evidence (V2 Phase 1 — migration 010) ─────────────────────────
// The accumulating evidence store. One row per chunk of source material a
// research run read. Embeddings power RAG; grounded_on arrays on artifacts
// point back here.

export type ResearchTrigger = "create" | "retry" | "refresh" | "manual" | "scheduled";
export type ResearchRunStatus = "running" | "done" | "failed";
export type EvidenceSourceTypeDb =
  | "website"
  | "search_result"
  | "competitor"
  | "industry"
  | "keyword"
  | "social"
  | "news"
  | "manual";

export interface DbResearchRun {
  id: string;
  brand_id: string;
  research_job_id: string | null;
  trigger: ResearchTrigger;
  facets: string[];
  status: ResearchRunStatus;
  started_at: string;
  completed_at: string | null;
  duration_ms: number | null;
  sources_collected: number;
  chunks_stored: number;
  chunks_embedded: number;
  tokens_input: number;
  tokens_output: number;
  cost_estimate_usd: number | null;
  intelligence_version: number | null;
  error_message: string | null;
  created_at: string;
}

export interface DbResearchDocument {
  id: string;
  brand_id: string;
  run_id: string | null;
  /** Groups all chunks of one captured source (Phase 1.5, migration 011). */
  source_id: string | null;
  /** BCP-47-ish language tag; drives FTS config choice (Phase 1.5). */
  language: string;
  source_type: EvidenceSourceTypeDb;
  url: string | null;
  domain: string | null;
  title: string | null;
  content: string;
  chunk_index: number;
  content_hash: string;
  summary: string | null;
  entities: Record<string, unknown> | null;
  keywords: string[] | null;
  /** Serialized vector — selected as string via PostgREST; null until embedded. */
  embedding: string | null;
  embedding_model: string | null;
  captured_at: string;
  freshness_ttl_days: number;
  deleted_by_user: boolean;
  metadata: Record<string, unknown>;
}

export interface DbBrandResearchJob {
  id: string;
  brand_id: string;
  status: ResearchJobStatus;
  current_step: string | null;
  progress: number;
  logs: ResearchLogEntry[];
  error_message: string | null;
  bull_job_id: string | null;
  started_at: string;
  completed_at: string | null;
}

export interface DbCompetitor {
  id: string;
  brand_id: string;
  name: string;
  website: string | null;
  summary: string | null;
  source: string | null;
  positioning: string | null;
  strengths: string[];
  weaknesses: string[];
  created_at: string;
  /** Phase 1.5 — search evidence backing this competitor analysis. */
  grounded_on?: string[];
}

/** Phase 1.5 — intelligence history: one snapshot per profile rewrite. */
export interface DbBrandIntelligenceVersion {
  id: string;
  brand_id: string;
  version: number;
  run_id: string | null;
  profile: BrandProfile;
  citations: Record<string, string[]>;
  source: "research" | "user_edit" | "optimizer";
  created_at: string;
}

export interface DbKeyword {
  id: string;
  brand_id: string;
  term: string;
  intent: string | null;
  search_volume: number | null;
  competition_score: number | null;
  trend_score: number | null;
  relevance_score: number | null;
  opportunity_score: number | null;
  created_at: string;
}

export interface DbContentPillar {
  id: string;
  brand_id: string;
  name: string;
  description: string | null;
  content_types: string[];
  example_topics: string[];
  priority: number;
  created_at: string;
}

// ─── Brand Topics (Phase 1) ──────────────────────────────────────────────────
// Gemini-generated content topic ideas attached to a researched brand.
// Surface them on /brands/[id] and in the Video Pipeline topic picker so
// users can drive video generation from authentic, on-brand angles instead
// of free-form prompts.

export type BrandTopicCategory =
  | "educational"
  | "storytelling"
  | "ugc"
  | "product-demo"
  | "listicle"
  | "problem-solution"
  | "founder-story";

export type BrandTopicStatus = "draft" | "used" | "archived";

export interface DbBrandTopic {
  id: string;
  brand_id: string;
  title: string;
  description: string | null;
  category: BrandTopicCategory | null;
  source: "ai-generated" | "manual" | "seo-keyword" | "evidence-mined";
  status: BrandTopicStatus;
  seed_keyword: string | null;
  hook_angle: string | null;
  created_at: string;
  used_at: string | null;
  use_count: number;
  // V2 Phase 1 — ideas are the bridge between research and content
  /** research_documents ids this idea was grounded on (coarse for now). */
  grounded_on: string[];
  /** Future Ideation-agent score (0-1); null = unscored. */
  confidence: number | null;
  /** Rolled-up performance of descendant artifacts (filled by Analyst later). */
  performance: Record<string, unknown>;
  // V2 Phase 2C — evidence-mined opportunities (migration 013)
  /** Why this idea exists, written against the cited evidence. */
  rationale?: string | null;
  /** Detection lens: pain_point | theme | competitor_gap | trend. */
  opportunity_kind?: "pain_point" | "theme" | "competitor_gap" | "trend" | null;
}

// ─── Scene Generations (Phase 6) ─────────────────────────────────────────────
// Per-scene provenance for the multi-scene Video Pipeline. Each render_job
// row has N scene_generations rows (3-6, matching storyboard.scenes.length).

export interface DbSceneGeneration {
  id: string;
  render_job_id: string;
  scene_number: number;             // 1-based to match storyboard.scenes[].index
  prompt: string;
  shot_type: string | null;
  provider: string;                 // 'runway' | 'luma' | 'pexels'
  clip_url: string | null;          // null while still generating
  duration_sec: number | null;
  width: number | null;
  height: number | null;
  generation_time_ms: number | null;
  cost_usd: number | null;
  fallback_reason: string | null;   // populated when primary provider(s) errored
  attribution: string | null;
  metadata: Record<string, unknown> | null;
  created_at: string;
}

// ─── User Budgets + AI Usage Ledger (B1.R1) ─────────────────────────────────

export interface DbUserBudget {
  user_id: string;
  monthly_hard_cap_usd: number;
  monthly_soft_cap_usd: number;
  current_month_used_usd: number;
  current_month_start: string;          // YYYY-MM-DD
  is_capped: boolean;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface DbAIUsageLedgerEntry {
  id: string;
  user_id: string;
  render_job_id: string | null;
  provider: "gemini" | "elevenlabs" | "runway" | "luma" | string;
  operation: string;
  cost_usd: number;
  units: number | null;
  unit_type: "tokens" | "chars" | "seconds" | "clips" | string | null;
  metadata: Record<string, unknown> | null;
  created_at: string;
}

// ─── Video keyword overlay (Phase 3) ─────────────────────────────────────────
// Output of extractImportantWords() — the high-impact words/phrases pulled
// from the script with millisecond-precision timing so the FFmpeg overlay
// renderer (Phase 4) can drop them on-screen viral-style.

export interface KeywordOverlay {
  text: string;        // ALL CAPS, 1-3 words
  start: number;       // seconds from video start
  end: number;         // seconds from video start
  emphasis?: "normal" | "punch" | "highlight"; // visual treatment hint
}

export interface KeywordOverlayBundle {
  keywords: KeywordOverlay[];
  estimatedNarrationSec: number;
}

// ─── Supabase Database definition ────────────────────────────────────────────
// Each table must include `Relationships: []` (or a proper relationship array)
// to satisfy postgrest-js's `GenericTable` constraint — without it the type
// resolver falls back to `never` and every `.insert()` looks like `never[]`.
// Insert/Update stay loose (Partial<Row>) so the deep inference doesn't choke.

type TableDef<Row> = {
  Row: Row;
  Insert: Partial<Row> & Record<string, unknown>;
  Update: Partial<Row>;
  Relationships: [];
};

export interface Database {
  public: {
    Tables: {
      projects:            TableDef<DbProject>;
      content_items:       TableDef<DbContentItem>;
      render_jobs:         TableDef<DbRenderJob>;
      activity:            TableDef<DbActivityItem>;
      brands:              TableDef<DbBrand>;
      brand_research_jobs: TableDef<DbBrandResearchJob>;
      competitors:         TableDef<DbCompetitor>;
      keywords:            TableDef<DbKeyword>;
      content_pillars:     TableDef<DbContentPillar>;
      brand_topics:        TableDef<DbBrandTopic>;
      scene_generations:   TableDef<DbSceneGeneration>;
      user_budgets:        TableDef<DbUserBudget>;
      ai_usage_ledger:     TableDef<DbAIUsageLedgerEntry>;
      campaigns:           TableDef<DbCampaign>;
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}

// ─── API / UI types ───────────────────────────────────────────────────────────

export interface GenerateRequest {
  // Legacy free-form prompt path (still supported for backwards compat)
  prompt?: string;
  // Phase 2 brand-driven path. When both are present, brand+topic wins
  // and the topic's title/hook_angle/description is used to construct
  // the prompt internally.
  brandId?: string;
  topicId?: string;
  // Style controls hook/voice/visuals — maps to BrandTopicCategory
  style?: string;
  provider?: "veo3" | "higgsfield" | "imagen3";
  sceneCount?: number;
  musicVibe?: string;
  renderVariant?: string;
  hookStyle?: string;
  projectId?: string;
}

export interface SSEEvent {
  type: "log" | "status" | "done" | "error";
  level?: "info" | "warn" | "error" | "success";
  message?: string;
  label?: string;
  pct?: number;
  videoUrl?: string;
  jobId?: string;
  error?: string;
  // Audio narration + music track URLs, attached to the `done` event so
  // the page can render "Hear narration" + "Preview music" CTAs.
  audioUrl?: string;
  musicUrl?: string;
  musicTrack?: string;
  // Attribution for the rendered video (e.g. "Photographer Name via
  // Pexels"). Pexels free tier requires displaying credit wherever their
  // footage is used.
  videoAttribution?: string;
  // Upload-ready post copy (title + description + hashtags) generated
  // alongside the video so users can paste it straight into the
  // platform upload flow.
  seo?: {
    title: string;
    description: string;
    hashtags: string[];
  };
}

export interface KPISummary {
  totalContent: number;
  totalVideos: number;
  creditsUsed: number;
  creditsTotal: number;
  activeProjects: number;
  publishedToday: number;
  renderQueue: number;
}

// One bucket in the daily analytics series (last 14 days).
export interface ChartPoint {
  date: string;     // formatted label e.g. "May 1"
  content: number;  // content_items created that day
  videos: number;   // render_jobs completed that day
  credits: number;  // approximated daily credit spend
}

export interface CreateBrandRequest {
  name: string;
  website: string;
  industry: string;
}
