// ─── Database schema types (mirrors Supabase tables) ─────────────────────────

export type ProjectStatus = "active" | "completed" | "draft" | "paused";
export type PipelineType = "content" | "video";
export type ContentStatus = "draft" | "approved" | "published" | "scheduled";
export type RenderStatus = "queued" | "rendering" | "done" | "failed";
export type ContentPlatform =
  | "linkedin"
  | "facebook"
  | "instagram"
  | "twitter"
  | "blog"
  | "email";

export type BrandStatus = "pending" | "researching" | "ready" | "failed";
export type ResearchJobStatus = "queued" | "running" | "done" | "failed";

// ─── BrandProfile — structured output of the Research agent ──────────────────

export interface BrandProfileService {
  name: string;
  description: string;
}
export interface BrandProfilePersona {
  name: string;
  role: string;
  goals: string[];
  pain_points: string[];
  channels: string[];
}
export interface BrandProfileVoice {
  tone: string[];                // ['authoritative','approachable']
  vocabulary_dos: string[];
  vocabulary_donts: string[];
  example_phrases: string[];
}
export interface BrandProfileAudience {
  demographics: string[];
  psychographics: string[];
  geographies: string[];
}
export interface BrandProfileICP {
  industries: string[];
  company_sizes: string[];       // ['SMB','Mid-market','Enterprise']
  roles: string[];
  pain_points: string[];
}

export interface BrandProfile {
  summary: string;
  positioning_statement: string;
  value_propositions: string[];
  services: BrandProfileService[];
  products: BrandProfileService[];
  offers: string[];
  brand_voice: BrandProfileVoice;
  audience: BrandProfileAudience;
  icp: BrandProfileICP;
  personas: BrandProfilePersona[];
  // Seed data the research agent emits alongside the profile.
  seed_keywords: string[];
  seed_competitors: string[];    // names only — the competitor agent enriches
}

// ─── Research job log entry ──────────────────────────────────────────────────

export interface ResearchLogEntry {
  ts: string;                    // ISO timestamp
  level: "info" | "warn" | "error" | "success";
  step: string;                  // matches DbBrandResearchJob.current_step values
  message: string;
  meta?: Record<string, unknown>;
}

// ─── Row types ────────────────────────────────────────────────────────────────

export interface DbProject {
  id: string;
  user_id: string;               // Clerk user id (text)
  name: string;
  type: PipelineType;
  status: ProjectStatus;
  created_at: string;
  updated_at: string;
  content_count: number;
  video_count: number;
  tags: string[];
  credits_used: number;
  brand_id: string | null;
}

export interface DbContentItem {
  id: string;
  project_id: string | null;
  // brand_id + user_prompt added in migration 003 to support the
  // direct-from-brand content generation flow (no project needed)
  brand_id?: string | null;
  user_prompt?: string | null;
  platform: ContentPlatform;
  title: string;
  preview: string | null;
  body: string | null;
  status: ContentStatus;
  created_at: string;
  // Engagement union: legacy social metrics OR generated-content extras
  // (hashtags + cta) the worker writes back. Either-or, depending on whether
  // the item was generated by the AI flow or imported/scraped.
  engagement:
    | { likes: number; shares: number; comments: number }
    | { hashtags?: string[]; cta?: string | null }
    | null;
}

export interface DbRenderJob {
  id: string;
  project_id: string | null;
  name: string;
  status: RenderStatus;
  progress: number;
  started_at: string;
  completed_at: string | null;
  duration_ms: number | null;
  template: string;
  output_path: string | null;
  output_url: string | null;
  error_message: string | null;
  prompt: string | null;
  meta: Record<string, unknown> | null;
  // ─── migration 004 (merge) ──────────────────────────────────────────────────
  merged_video_url?: string | null;
  merge_status?: "pending" | "merging" | "done" | "failed" | null;
  merge_error?: string | null;
  // ─── migration 006 (full provenance + history) ──────────────────────────────
  user_id?: string | null;
  brand_id?: string | null;
  topic_id?: string | null;
  style?: string | null;
  script_json?: Record<string, unknown> | null;
  storyboard_json?: Record<string, unknown> | null;
  seo_json?: Record<string, unknown> | null;
  overlay_json?: { keywords: KeywordOverlay[] } | null;
  narration_url?: string | null;
  music_url?: string | null;
  music_track?: string | null;
  video_attribution?: string | null;
  created_at?: string;
}

export interface DbActivityItem {
  id: string;
  project_id: string | null;
  project_name: string | null;
  type:
    | "video_rendered"
    | "content_generated"
    | "project_created"
    | "approval"
    | "published"
    | "error"
    | "brand_researched";
  message: string;
  created_at: string;
  meta: Record<string, string> | null;
}

export interface DbBrand {
  id: string;
  user_id: string;
  name: string;
  website: string | null;
  industry: string | null;
  status: BrandStatus;
  profile: BrandProfile | null;
  brand_colors: Record<string, string> | null;
  logo_url: string | null;
  created_at: string;
  updated_at: string;
}

export interface DbBrandResearchJob {
  id: string;
  brand_id: string;
  status: ResearchJobStatus;
  current_step: string | null;
  progress: number;
  logs: ResearchLogEntry[];
  error_message: string | null;
  bull_job_id: string | null;
  started_at: string;
  completed_at: string | null;
}

export interface DbCompetitor {
  id: string;
  brand_id: string;
  name: string;
  website: string | null;
  summary: string | null;
  source: string | null;
  positioning: string | null;
  strengths: string[];
  weaknesses: string[];
  created_at: string;
}

export interface DbKeyword {
  id: string;
  brand_id: string;
  term: string;
  intent: string | null;
  search_volume: number | null;
  competition_score: number | null;
  trend_score: number | null;
  relevance_score: number | null;
  opportunity_score: number | null;
  created_at: string;
}

export interface DbContentPillar {
  id: string;
  brand_id: string;
  name: string;
  description: string | null;
  content_types: string[];
  example_topics: string[];
  priority: number;
  created_at: string;
}

// ─── Brand Topics (Phase 1) ──────────────────────────────────────────────────
// Gemini-generated content topic ideas attached to a researched brand.
// Surface them on /brands/[id] and in the Video Pipeline topic picker so
// users can drive video generation from authentic, on-brand angles instead
// of free-form prompts.

export type BrandTopicCategory =
  | "educational"
  | "storytelling"
  | "ugc"
  | "product-demo"
  | "listicle"
  | "problem-solution"
  | "founder-story";

export type BrandTopicStatus = "draft" | "used" | "archived";

export interface DbBrandTopic {
  id: string;
  brand_id: string;
  title: string;
  description: string | null;
  category: BrandTopicCategory | null;
  source: "ai-generated" | "manual" | "seo-keyword";
  status: BrandTopicStatus;
  seed_keyword: string | null;
  hook_angle: string | null;
  created_at: string;
  used_at: string | null;
  use_count: number;
}

// ─── Scene Generations (Phase 6) ─────────────────────────────────────────────
// Per-scene provenance for the multi-scene Video Pipeline. Each render_job
// row has N scene_generations rows (3-6, matching storyboard.scenes.length).

export interface DbSceneGeneration {
  id: string;
  render_job_id: string;
  scene_number: number;             // 1-based to match storyboard.scenes[].index
  prompt: string;
  shot_type: string | null;
  provider: string;                 // 'runway' | 'luma' | 'pexels'
  clip_url: string | null;          // null while still generating
  duration_sec: number | null;
  width: number | null;
  height: number | null;
  generation_time_ms: number | null;
  cost_usd: number | null;
  fallback_reason: string | null;   // populated when primary provider(s) errored
  attribution: string | null;
  metadata: Record<string, unknown> | null;
  created_at: string;
}

// ─── Video keyword overlay (Phase 3) ─────────────────────────────────────────
// Output of extractImportantWords() — the high-impact words/phrases pulled
// from the script with millisecond-precision timing so the FFmpeg overlay
// renderer (Phase 4) can drop them on-screen viral-style.

export interface KeywordOverlay {
  text: string;        // ALL CAPS, 1-3 words
  start: number;       // seconds from video start
  end: number;         // seconds from video start
  emphasis?: "normal" | "punch" | "highlight"; // visual treatment hint
}

export interface KeywordOverlayBundle {
  keywords: KeywordOverlay[];
  estimatedNarrationSec: number;
}

// ─── Supabase Database definition ────────────────────────────────────────────
// Each table must include `Relationships: []` (or a proper relationship array)
// to satisfy postgrest-js's `GenericTable` constraint — without it the type
// resolver falls back to `never` and every `.insert()` looks like `never[]`.
// Insert/Update stay loose (Partial<Row>) so the deep inference doesn't choke.

type TableDef<Row> = {
  Row: Row;
  Insert: Partial<Row> & Record<string, unknown>;
  Update: Partial<Row>;
  Relationships: [];
};

export interface Database {
  public: {
    Tables: {
      projects:            TableDef<DbProject>;
      content_items:       TableDef<DbContentItem>;
      render_jobs:         TableDef<DbRenderJob>;
      activity:            TableDef<DbActivityItem>;
      brands:              TableDef<DbBrand>;
      brand_research_jobs: TableDef<DbBrandResearchJob>;
      competitors:         TableDef<DbCompetitor>;
      keywords:            TableDef<DbKeyword>;
      content_pillars:     TableDef<DbContentPillar>;
      brand_topics:        TableDef<DbBrandTopic>;
      scene_generations:   TableDef<DbSceneGeneration>;
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}

// ─── API / UI types ───────────────────────────────────────────────────────────

export interface GenerateRequest {
  // Legacy free-form prompt path (still supported for backwards compat)
  prompt?: string;
  // Phase 2 brand-driven path. When both are present, brand+topic wins
  // and the topic's title/hook_angle/description is used to construct
  // the prompt internally.
  brandId?: string;
  topicId?: string;
  // Style controls hook/voice/visuals — maps to BrandTopicCategory
  style?: string;
  provider?: "veo3" | "higgsfield" | "imagen3";
  sceneCount?: number;
  musicVibe?: string;
  renderVariant?: string;
  hookStyle?: string;
  projectId?: string;
}

export interface SSEEvent {
  type: "log" | "status" | "done" | "error";
  level?: "info" | "warn" | "error" | "success";
  message?: string;
  label?: string;
  pct?: number;
  videoUrl?: string;
  jobId?: string;
  error?: string;
  // Audio narration + music track URLs, attached to the `done` event so
  // the page can render "Hear narration" + "Preview music" CTAs.
  audioUrl?: string;
  musicUrl?: string;
  musicTrack?: string;
  // Attribution for the rendered video (e.g. "Photographer Name via
  // Pexels"). Pexels free tier requires displaying credit wherever their
  // footage is used.
  videoAttribution?: string;
  // Upload-ready post copy (title + description + hashtags) generated
  // alongside the video so users can paste it straight into the
  // platform upload flow.
  seo?: {
    title: string;
    description: string;
    hashtags: string[];
  };
}

export interface KPISummary {
  totalContent: number;
  totalVideos: number;
  creditsUsed: number;
  creditsTotal: number;
  activeProjects: number;
  publishedToday: number;
  renderQueue: number;
}

// One bucket in the daily analytics series (last 14 days).
export interface ChartPoint {
  date: string;     // formatted label e.g. "May 1"
  content: number;  // content_items created that day
  videos: number;   // render_jobs completed that day
  credits: number;  // approximated daily credit spend
}

export interface CreateBrandRequest {
  name: string;
  website: string;
  industry: string;
}
