/**
 * Pre-render cost estimation (Video V1 hardening — Cost Approval Gate).
 *
 * Computes the expected Seedance spend for a frozen VideoStrategy BEFORE any
 * provider call, so POST /api/video/generate can require explicit approval and
 * surface a dollar figure. Uses the SAME billable-duration rounding and
 * per-second rate as the live provider (src/lib/video-providers/seedance.ts) so
 * the estimate matches the ledger.
 *
 * This is an upper-bound estimate for the primary path (every scene via
 * Seedance). If a scene falls through to free Pexels the real cost is lower;
 * paid Runway/Luma fallbacks are off by default (see video/flags.ts).
 */
import { seedanceDuration, seedancePerSecondUsd } from "@/lib/video-providers/seedance";
import type { VideoStrategy } from "@/lib/ffmpeg-pipeline/types";

export interface SceneCostLine {
  sceneId: number;
  requestedDurationSec: number;
  billableDurationSec: number;
  estimatedCostUsd: number;
}

export interface RenderCostEstimate {
  provider: "seedance";
  sceneCount: number;
  perSecondUsd: number;
  totalBillableSeconds: number;
  estimatedCostUsd: number;
  perScene: SceneCostLine[];
  note: string;
}

/** Round a USD figure to 4 dp (sub-cent precision for small per-scene costs). */
function round4(n: number): number {
  return Math.round(n * 10_000) / 10_000;
}

export function estimateRenderCost(strategy: VideoStrategy): RenderCostEstimate {
  const rate = seedancePerSecondUsd();
  const perScene: SceneCostLine[] = strategy.scenes.map((s) => {
    const billable = seedanceDuration(s.durationSec);
    return {
      sceneId: s.sceneId,
      requestedDurationSec: s.durationSec,
      billableDurationSec: billable,
      estimatedCostUsd: round4(billable * rate),
    };
  });
  const totalBillableSeconds = perScene.reduce((a, l) => a + l.billableDurationSec, 0);
  return {
    provider: "seedance",
    sceneCount: perScene.length,
    perSecondUsd: rate,
    totalBillableSeconds,
    estimatedCostUsd: round4(totalBillableSeconds * rate),
    perScene,
    note: "Upper bound: assumes every scene is generated by Seedance. Pexels fallback (free) lowers actual cost; paid Runway/Luma fallbacks are off unless explicitly enabled.",
  };
}
