/**
 * Pre-render cost estimation (Video V1 hardening — Cost Approval Gate).
 *
 * Computes the expected Seedance spend for a frozen VideoStrategy BEFORE any
 * provider call, so POST /api/video/generate can require explicit approval and
 * surface a dollar figure. Uses the SAME billable-duration rounding and
 * per-second rate as the live provider (src/lib/video-providers/seedance.ts) so
 * the estimate matches the ledger.
 *
 * This is an upper-bound estimate for the primary path (every scene via
 * Seedance). If a scene falls through to free Pexels the real cost is lower;
 * paid Runway/Luma fallbacks are off by default (see video/flags.ts).
 */
import { seedanceDuration, seedancePerSecondUsd } from "@/lib/video-providers/seedance";
import type { VideoStrategy } from "@/lib/ffmpeg-pipeline/types";

export interface SceneCostLine {
  sceneId: number;
  requestedDurationSec: number;
  billableDurationSec: number;
  estimatedCostUsd: number;
}

export type Resolution = "720p" | "1080p";

/** Resolution cost multiplier. HARDENING (Sprint 4.1): 1080p is NOT yet wired
 * end-to-end (the worker/Seedance render the 720p source regardless), so we do
 * NOT charge a different rate for it — pricing must reflect the real pipeline.
 * Returns 1 for every tier until 1080p source generation actually ships; then
 * recalibrate against a real 1080p render. (Kept as a function so the call sites
 * and the future wiring point are explicit.) */
export function resolutionRateMultiplier(_resolution: Resolution = "720p"): number {
  return 1;
}

/** Pre-render cost split for the modal breakdown. Scene generation is the only
 * paid line today (Seedance); Story is one cheap Gemini call; Composition and
 * Rendering run on our own FFmpeg compute (no marginal provider cost). */
export interface CostBreakdown {
  storyUsd: number;
  sceneGenerationUsd: number;
  compositionUsd: number;
  renderingUsd: number;
}

export interface RenderCostEstimate {
  provider: "seedance";
  sceneCount: number;
  perSecondUsd: number;
  totalBillableSeconds: number;
  estimatedCostUsd: number;
  perScene: SceneCostLine[];
  note: string;
  // ── Sprint 4 (additive; older callers ignore these) ──
  resolution: Resolution;
  breakdown: CostBreakdown;
  /** Estimated end-to-end render time (seconds) — scene gen dominates. */
  estRenderTimeSec: number;
}

/** Round a USD figure to 4 dp (sub-cent precision for small per-scene costs). */
function round4(n: number): number {
  return Math.round(n * 10_000) / 10_000;
}

/** Fixed, negligible Story (Gemini Flash) cost surfaced in the breakdown. */
const STORY_USD = 0.01;
/** Rough per-scene Seedance generation wall-time (s) — calibrated from b1807d29
 * (~2.5 min/scene under load). Compose adds a near-fixed tail. */
const PER_SCENE_GEN_SEC = 150;
const COMPOSE_TAIL_SEC = 35;

export function estimateRenderCost(
  strategy: VideoStrategy,
  opts?: { resolution?: Resolution },
): RenderCostEstimate {
  const resolution: Resolution = opts?.resolution ?? "720p";
  const rate = seedancePerSecondUsd() * resolutionRateMultiplier(resolution);
  const perScene: SceneCostLine[] = strategy.scenes.map((s) => {
    const billable = seedanceDuration(s.durationSec);
    return {
      sceneId: s.sceneId,
      requestedDurationSec: s.durationSec,
      billableDurationSec: billable,
      estimatedCostUsd: round4(billable * rate),
    };
  });
  const totalBillableSeconds = perScene.reduce((a, l) => a + l.billableDurationSec, 0);
  const sceneGenerationUsd = round4(totalBillableSeconds * rate);
  return {
    provider: "seedance",
    sceneCount: perScene.length,
    perSecondUsd: rate,
    totalBillableSeconds,
    // Headline = the AtlasCloud/Seedance spend ONLY (what the balance preflight
    // must cover). Story is a Google/Gemini cost shown separately in `breakdown`,
    // not added here — keeps the certified estimate exact ($5.00) + preflight correct.
    estimatedCostUsd: sceneGenerationUsd,
    perScene,
    note: "Upper bound: assumes every scene is generated by Seedance. Pexels fallback (free) lowers actual cost; paid Runway/Luma fallbacks are off unless explicitly enabled.",
    resolution,
    breakdown: {
      storyUsd: STORY_USD,
      sceneGenerationUsd,
      compositionUsd: 0,
      renderingUsd: 0,
    },
    estRenderTimeSec: perScene.length * PER_SCENE_GEN_SEC + COMPOSE_TAIL_SEC,
  };
}
