-- 005_brand_topics.sql
-- Adds the Brand Topics engine — Gemini-generated content topic ideas
-- attached to each researched brand, so the Video Pipeline (and future
-- Content Pipeline flows) can be driven by an authentic, on-brand topic
-- instead of asking the user to write a free-form prompt every time.
--
-- Generated by the brand_research worker as a best-effort 6th step
-- (failures don't fail the whole research job — the brand is still
-- usable, just without auto-generated topics. User can hit a manual
-- "Regenerate topics" endpoint if so).

CREATE TABLE IF NOT EXISTS brand_topics (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_id      UUID NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  title         TEXT NOT NULL,
  description   TEXT,
  category      TEXT,           -- educational | storytelling | ugc | product-demo | listicle | problem-solution | founder-story
  source        TEXT NOT NULL DEFAULT 'ai-generated', -- ai-generated | manual | seo-keyword
  status        TEXT NOT NULL DEFAULT 'draft',         -- draft | used | archived
  seed_keyword  TEXT,
  hook_angle    TEXT,           -- one-line angle / hook the topic was conceived around
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  used_at       TIMESTAMPTZ,
  use_count     INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT brand_topics_category_check
    CHECK (category IS NULL OR category IN (
      'educational','storytelling','ugc','product-demo',
      'listicle','problem-solution','founder-story'
    )),
  CONSTRAINT brand_topics_status_check
    CHECK (status IN ('draft','used','archived'))
);

CREATE INDEX IF NOT EXISTS brand_topics_brand_id_idx ON brand_topics(brand_id);
CREATE INDEX IF NOT EXISTS brand_topics_status_idx   ON brand_topics(status);
CREATE INDEX IF NOT EXISTS brand_topics_category_idx ON brand_topics(category);

-- ─── RLS ─────────────────────────────────────────────────────────────────────
-- Topics traverse brand_id → brands.user_id, same pattern as content_items
-- did in migration 003. Worker writes via service_role (bypasses RLS).
ALTER TABLE brand_topics ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "brand_topics_owner_select" ON brand_topics;
CREATE POLICY "brand_topics_owner_select"
  ON brand_topics FOR SELECT
  USING (
    brand_id IN (
      SELECT id FROM brands
      WHERE user_id = current_clerk_user_id()
    )
  );

DROP POLICY IF EXISTS "brand_topics_owner_update" ON brand_topics;
CREATE POLICY "brand_topics_owner_update"
  ON brand_topics FOR UPDATE
  USING (
    brand_id IN (
      SELECT id FROM brands
      WHERE user_id = current_clerk_user_id()
    )
  );

-- INSERT only by service_role (worker) — no policy for end-user inserts.

-- ─── Realtime publication ────────────────────────────────────────────────────
-- Stream new topic rows to the brand detail page in real time as the worker
-- generates them.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND tablename = 'brand_topics'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE brand_topics;
  END IF;
END $$;
