-- 020_creative_background_source.sql
-- Records how a creative's background was produced:
--   'imagen'   — generated by Imagen and passed safety validation
--   'fallback' — deterministic palette gradient (sharp only, never Imagen),
--                used when Imagen's background failed text/logo/face validation
--                after all attempts so the creative still produces an image.
-- Additive, nullable. Powers visual attribution (background_source).

ALTER TABLE content_creatives ADD COLUMN IF NOT EXISTS background_source TEXT;
