/**
 * Platform content validation (Sprint 4.x — production config UI).
 *
 * PURE, deterministic checks of post copy against each platform's published
 * limits. Used PRE-render to surface pass/fail in the configurator and to gate
 * the Generate button. It NEVER trims or mutates content — it only reports
 * validity so the operator can regenerate. No network, no side effects.
 *
 * Rules are the platform spec (caption/title/description length + hashtag count).
 */
import type { Platform } from "./profiles";

export interface ContentLimits {
  /** Caption / post body character bounds. */
  caption: { min: number; max: number };
  /** Hashtag count bounds. */
  hashtags: { min: number; max: number };
  /** YouTube-style title cap (chars), when the platform uses a title. */
  titleMax?: number;
  /** YouTube-style description cap (chars), when applicable. */
  descriptionMax?: number;
}

/** Per-platform limits, keyed to the 9 Platform Agent ids. */
export const CONTENT_LIMITS: Record<Platform, ContentLimits> = {
  linkedin: { caption: { min: 300, max: 1200 }, hashtags: { min: 3, max: 5 } },
  tiktok: { caption: { min: 0, max: 150 }, hashtags: { min: 3, max: 8 } },
  instagram_reels: { caption: { min: 0, max: 2200 }, hashtags: { min: 5, max: 15 } },
  instagram_feed: { caption: { min: 0, max: 2200 }, hashtags: { min: 5, max: 15 } },
  facebook_reels: { caption: { min: 40, max: 250 }, hashtags: { min: 2, max: 5 } },
  facebook_feed: { caption: { min: 40, max: 250 }, hashtags: { min: 2, max: 5 } },
  youtube_shorts: { caption: { min: 0, max: 5000 }, hashtags: { min: 3, max: 5 }, titleMax: 100, descriptionMax: 5000 },
  youtube_standard: { caption: { min: 0, max: 5000 }, hashtags: { min: 3, max: 8 }, titleMax: 100, descriptionMax: 5000 },
  x: { caption: { min: 0, max: 280 }, hashtags: { min: 1, max: 3 } },
};

export interface ContentInput {
  caption?: string | null;
  hashtags?: string[] | null;
  title?: string | null;
  description?: string | null;
}

export interface FieldCheck {
  field: "caption" | "hashtags" | "title" | "description";
  ok: boolean;
  actual: number;
  rule: string;
}

export interface ContentValidationResult {
  ok: boolean;
  platform: Platform;
  checks: FieldCheck[];
}

/**
 * Validate post copy against a platform's limits. Returns per-field results +
 * an overall `ok`. Does NOT mutate or trim — invalid content should be
 * regenerated by the caller, never silently cut.
 */
export function validatePlatformContent(platform: Platform, input: ContentInput): ContentValidationResult {
  const limits = CONTENT_LIMITS[platform];
  const checks: FieldCheck[] = [];

  const captionLen = (input.caption ?? "").trim().length;
  checks.push({
    field: "caption",
    ok: captionLen >= limits.caption.min && captionLen <= limits.caption.max,
    actual: captionLen,
    rule: limits.caption.min > 0 ? `${limits.caption.min}–${limits.caption.max} chars` : `≤ ${limits.caption.max} chars`,
  });

  const tagCount = (input.hashtags ?? []).filter((h) => (h ?? "").trim().length > 0).length;
  checks.push({
    field: "hashtags",
    ok: tagCount >= limits.hashtags.min && tagCount <= limits.hashtags.max,
    actual: tagCount,
    rule: `${limits.hashtags.min}–${limits.hashtags.max} hashtags`,
  });

  if (limits.titleMax != null) {
    const titleLen = (input.title ?? "").trim().length;
    checks.push({ field: "title", ok: titleLen > 0 && titleLen <= limits.titleMax, actual: titleLen, rule: `≤ ${limits.titleMax} chars` });
  }
  if (limits.descriptionMax != null) {
    const descLen = (input.description ?? "").trim().length;
    checks.push({ field: "description", ok: descLen <= limits.descriptionMax, actual: descLen, rule: `≤ ${limits.descriptionMax} chars` });
  }

  return { ok: checks.every((c) => c.ok), platform, checks };
}
